"""user_role -> user_roles

Revision ID: 62bf7401881d
Revises: 42f4fac33c98
Create Date: 2026-03-21 01:21:29.002596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '62bf7401881d'
down_revision: Union[str, Sequence[str], None] = '42f4fac33c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userrole',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_type', sa.Enum('COMERCIAL', 'EXECUTOR', 'FINANCEIRO', 'ADMIN', name='roletype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_type')
    )
    op.create_table('rolelink',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['userrole.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'role_id')
    )
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=10), nullable=False))
    op.drop_table('rolelink')
    op.drop_table('userrole')
    # ### end Alembic commands ###
